
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CANJES.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_EncabezadoSAP
{

    public int Documento { get; set; }

    public string Cod_Casa_SAP { get; set; }

    public string Cod_Prov_SAP { get; set; }

    public string Cod_Cliente_SAP { get; set; }

    public string Sociedad { get; set; }

    public string Centro { get; set; }

    public string Cliente { get; set; }

    public string Observaciones { get; set; }

    public string Estado { get; set; }

    public System.DateTime Fecha_Autorizacion { get; set; }

    public System.DateTime Fecha_Migo { get; set; }

    public System.DateTime Fecha { get; set; }

    public int Id_Usuario { get; set; }

}

}
