
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CANJES.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TBL_UsuariosCanjes
{

    public int id { get; set; }

    public string nombreUsuario { get; set; }

    public string pass { get; set; }

    public string email { get; set; }

    public string token_recovery { get; set; }

    public Nullable<int> id_sociedad { get; set; }

    public Nullable<int> id_centro { get; set; }

    public Nullable<int> id_estado { get; set; }

    public Nullable<int> id_rol { get; set; }

}

}
