
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CANJES.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VSP_Casa_ClientePrv_Sociedad
{

    public string CodCasa { get; set; }

    public string Casa { get; set; }

    public string CodProvSAP { get; set; }

    public string Nombre_según_Proveedor { get; set; }

    public string CodClienteSAP { get; set; }

    public string CodSoc { get; set; }

    public string Sociedad { get; set; }

}

}
