
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CANJES.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VSP_ReporteLogs
{

    public int Documento { get; set; }

    public string Cod_Prod_SAP { get; set; }

    public string Nombre_SAP { get; set; }

    public string Nombre_Segun_Proveedor { get; set; }

    public decimal Cantidad_Solicitada { get; set; }

    public decimal Cantidad_Enviar { get; set; }

    public decimal Saldo_SAP { get; set; }

    public string UNIDAD { get; set; }

    public string Mensaje1 { get; set; }

    public string Mensaje2 { get; set; }

    public string Mensaje3 { get; set; }

    public string Mensaje4 { get; set; }

    public string Sociedad { get; set; }

    public string nombre_sociedad { get; set; }

    public string CENTRO { get; set; }

    public string nombre_centro { get; set; }

    public string Cliente { get; set; }

    public string Estado { get; set; }

    public System.DateTime Fecha_Autorizacion { get; set; }

    public string Observaciones { get; set; }

    public string nombreUsuario { get; set; }

    public string DOCUMENT_SAP { get; set; }

    public System.DateTime Fecha_Migo { get; set; }

    public string DOCUMENT_YEAR { get; set; }

}

}
