
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CANJES.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VSP_PROVEEDORES_SAP
{

    public string MANDT { get; set; }

    public string KUNNR { get; set; }

    public string LIFNR { get; set; }

    public string SORTL { get; set; }

    public string NAME1 { get; set; }

}

}
