
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CANJES.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VSP_CLIENTE_X_SOCIEDAD_SAP
{

    public string CODIGO_CLIENTE { get; set; }

    public string NOMBRE_CLIENTE { get; set; }

    public string SOCIEDAD_CLIENTE { get; set; }

}

}
