
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CANJES.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VSP_Autorizaciones_Detalle
{

    public int Documento { get; set; }

    public string Cod_Prod_SAP { get; set; }

    public string MAKTX { get; set; }

    public decimal Cantidad_Solicitada { get; set; }

    public decimal Cantidad_Enviar { get; set; }

    public decimal Saldo_SAP { get; set; }

    public string Mensaje1 { get; set; }

    public string Mensaje2 { get; set; }

    public string Mensaje3 { get; set; }

    public string Mensaje4 { get; set; }

    public string LOTE { get; set; }

    public string FECHA_CAD { get; set; }

    public int Particion { get; set; }

}

}
